# Generated by Django 4.2.7 on 2025-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for videos', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='text_overlay',
            field=models.TextField(blank=True, help_text='Text overlay for story images'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='text_position',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('middle', 'Middle'), ('bottom', 'Bottom')], default='middle', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Regular Post'), ('job', 'Job Posting'), ('short', 'Short Video'), ('story', 'Story (24h)'), ('ad', 'Advertisement')], max_length=20),
        ),
    ]
