# Generated by Django 4.2.7 on 2025-09-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmedia_duration_postmedia_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ad_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_advertisement',
            field=models.BooleanField(default=False),
        ),
    ]
