# Generated by Django 4.2.7 on 2025-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('premium_subscription', 'Premium Subscription'), ('post_boost', 'Post Boost'), ('content_monetization', 'Content Monetization'), ('ecommerce_purchase', 'E-commerce Purchase'), ('delivery_fee', 'Delivery Fee'), ('driver_payment', 'Driver Payment'), ('creator_reward', 'Creator Reward'), ('wallet_funding', 'Wallet Funding')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('cash_on_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('khalti', 'Khalti'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('digital_wallet', 'Digital Wallet')], max_length=20),
        ),
    ]
