# Generated by Django 4.2.7 on 2025-09-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
