# Generated by Django 4.2.7 on 2025-09-04 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_phone', models.CharField(max_length=20)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('delivery_address', models.TextField()),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('distance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_delivery_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Driver'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('priority_level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=50)),
                ('citizenship_photo', models.ImageField(upload_to='driver_docs/citizenship/')),
                ('driving_license_number', models.CharField(max_length=50)),
                ('driving_license_photo', models.ImageField(upload_to='driver_docs/license/')),
                ('profile_photo', models.ImageField(upload_to='driver_docs/photos/')),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('truck', 'Truck')], max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number_plate', models.CharField(max_length=20)),
                ('vehicle_photo', models.ImageField(upload_to='driver_docs/vehicles/')),
                ('vehicle_registration', models.ImageField(upload_to='driver_docs/registration/')),
                ('status', models.CharField(choices=[('pending', 'Application Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('late_delivery', 'Late Delivery'), ('no_show', 'No Show'), ('rude_behavior', 'Rude Behavior'), ('damaged_goods', 'Damaged Goods'), ('wrong_delivery', 'Wrong Delivery Address'), ('vehicle_issue', 'Vehicle Related Issue'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='delivery.deliveryorder')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='delivery.driver')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status_note', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='delivery.deliveryorder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('speed_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('politeness_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('care_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.deliveryorder')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='delivery.driver')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.driver'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='ecommerce_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='ecommerce.order'),
        ),
    ]
