# Generated by Django 4.2.7 on 2025-09-05 16:04

from django.db import migrations
from django.utils.text import slugify


def populate_shops(apps, schema_editor):
    """
    Create default shops for existing users who have products.
    """
    Product = apps.get_model('ecommerce', 'Product')
    Shop = apps.get_model('ecommerce', 'Shop')
    User = apps.get_model('accounts', 'User')
    
    # Get all users who have products
    users_with_products = User.objects.filter(
        products__isnull=False
    ).distinct()
    
    for user in users_with_products:
        # Create a default shop for the user
        shop_name = f"{user.username}'s Store"
        base_slug = slugify(shop_name)
        slug = base_slug
        counter = 1
        while Shop.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        shop = Shop.objects.create(
            owner=user,
            name=shop_name,
            description=f"Default shop for {user.username}",
            slug=slug
        )
        
        # Assign all user's products to this shop
        Product.objects.filter(seller=user, shop__isnull=True).update(shop=shop)


def reverse_populate_shops(apps, schema_editor):
    """
    Reverse the migration - remove default shops.
    """
    Shop = apps.get_model('ecommerce', 'Shop')
    Shop.objects.filter(name__endswith="'s Store").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_add_shop_model'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_shops, reverse_populate_shops),
    ]
