# Generated by Django 4.2.7 on 2025-09-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_followers_count_and_more'),
    ]

    operations = [
    ]
