# Generated by Django 4.2.7 on 2025-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription_userprofile_allow_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_years_at_apply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location_preference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI-calculated job match percentage', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='remote_preference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills_at_apply',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_letter_template',
            field=models.TextField(blank=True, help_text='Default cover letter template'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_start_date',
            field=models.DateField(blank=True, help_text='When user started their career', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Total years of experience', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Job type, experience level preferences'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, help_text='Preferred work locations'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remote_work_preference',
            field=models.CharField(blank=True, choices=[('on_site', 'On-site Only'), ('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of technical skills'),
        ),
    ]
