# Generated by Django 4.2.7 on 2025-09-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jobapplication_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allows_remote_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of company benefits'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_culture',
            field=models.TextField(blank=True, help_text='Describe company culture and values'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_hiring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes for verification'),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_type',
            field=models.CharField(choices=[('none', 'None'), ('blue', 'Blue Premium'), ('gold', 'Gold Premium')], default='none', max_length=10),
        ),
    ]
