# Generated by Django 4.2.7 on 2025-09-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_allows_remote_work_company_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='premium_type',
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_tick',
            field=models.CharField(choices=[('none', 'None'), ('blue', 'Blue Tick (LaliGurans Badge) 🌺'), ('gold', 'Golden Tick (Sagarmatha Badge) 🏔️'), ('business', 'Business Tick (Dhaka Badge) 🧵'), ('special', 'Special Tick (Pashupatinath Badge) 🕉️')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tick_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
