# Generated by Django 4.2.7 on 2025-09-06 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_premium_type_user_purchased_tick_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_premium',
            new_name='is_yearly_subscription',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='premium_expires_at',
            new_name='subscription_expires_at',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.IntegerField(choices=[(0, 'Free - 10 posts/day, 4 media/post, ads shown'), (1, 'Tier 1 - 20 posts/day, 8 media/post, no ads'), (2, 'Tier 2 - 40 posts/day, 16 media/post, no ads'), (3, 'Tier 3 - 80 posts/day, 32 media/post, no ads')], default=0),
        ),
        migrations.CreateModel(
            name='TierSubscriptionPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tier', models.IntegerField(default=0)),
                ('to_tier', models.IntegerField()),
                ('is_yearly', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
